### ISSUE TITLE
Wrong semantics of re-declarations

### ISSUE THREAD

**Issue by chengluyu** [hkust-taco/mlscript#49]
Look at this example first.

Code:

```
def x = 0
def getX () = x
def x = 1
def y = getX ()
```

Types and results:

```
val x: 0 = 0
val getX: () -> 0 = () => x
val x: 1 = 1
val y: 0 = 1 // <---- notice this
```

My current solution is to rebind the re-declared `x` to another name. For example, generated code should be like this:

```js
let x = 0;
let getX = () => x;
let x0 = 1;
let y = getX(); // Evaluates to `0`, which matches the type.
```

**Comment by LPTK** [comment]
Wasn't this already done?

If you were using mutation instead, it was definitely the wrong semantics. ML-style let shadowing is nothing more than using the same name for completely distinct variables. It's not like mutation.

That's why a long time ago I suggested a first pass to rename every variable in the program to a unique name. But I think your proposed solution of renaming on the fly only what needs to be renamed is a bit better for generated code readability.

**Comment by chengluyu** [comment]
😅 Unfortunately the current implementation mutates old variables.

**Comment by chengluyu** [comment]
I renamed the issue making it more accurate. 🤔
